export default {
  font: {
    fontFamily: 'Ubuntu, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial, Lucida Grande, sans-serif',
    fontSize: null,
  },
  topbar: {
    topbarBgColor: '#0D3650',
    topbarItemTextColor: '#ffffff',
    topbarTextColor: '#ffffff',
    topbarLeftBgColor: '#0D3650',
    topbarItemTextHoverBgColor: '#262626',
    topbarMenuButtonBgColor: 'rgb(255 0 68)',
    logoColor: '#ffffff',
  },
  sidebar: {
    menuTextColor: '#274B5F',
    menuBgColor: ' #fdfeff',
    menuItemTextColor: ' #515c66',
    menuItemBgColor: null,
    menuItemHoverBgColor: '#d0021b',
    menuActiveItemTextColor: '#515c66',
    menuActiveItemBgColor: 'rgba(0, 0, 0, 0.04)',
    menuInlineBorderColor: null,
  },
  general: {
    primaryColor: '#274B5F',
    secondaryColor: '#1C4257',
    textColor: 'rgba(0, 0, 0, 0.87)',
    textSecondaryColor: '#262626',
    bodyBgColor: '#f7f7f7',
    contentBgColor: '#ffffff',
    contentAltBgColor: null,
    overlayContentBgColor: '#ffffff',
    hoverBgColor: '#ad1457',
    solidSurfaceTextColor: '#ffffff',
    dividerColor: '#e4e4e4',
    buttonHoverBg: '#ad1457',
    buttonActiveBg: 'rgba(39, 75, 95, 0.68)',
    dangerButtonBg: '#D32F2F',
    infoMessageBg: '#b3e5fc',
    successMessageBg: '#c8e6c9',
    warningMessageBg: '#ffecb3',
    errorMessageBg: '#ffcdd2',
  },
}
